// <auto-generated />
namespace Euphoria.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class roletableAddeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(roletableAddeded));
        
        string IMigrationMetadata.Id
        {
            get { return "202109271742289_roletableAddeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
